### ISSUE TITLE
3 incorrect bytes in asm file

### ISSUE THREAD

**Issue by Ian-May** [tgtakaoka/LILbug#1]
I did a direct binary comparison of the Motorola listing and an assembled version of your asm file and found the following issues.
1) Line 350 At label HY you have LDD #$0095 which should be LDD #$0005 - wouldn't affect 6801 - problem with Hitachi 6301XY.
2) Line 799 you have BSR OUT2HS should be BSR OUT2H (no space after 2 hex digits)
3) Line 1583 you have QMARK FCB $34,4 should be FCB $3F,4 i.e. '?' - would print "4" not "?" for errors - see comments lines 484-486
Thanks for sharing your work.

**Comment by tgtakaoka** [comment]
Hi, Ian.
Thank you for your valuable report.
Yes I just assemble the code and hasn't have a chance to run it on a real CPU.

I'll fix the 3 bytes as soon as possible.

**Comment by tgtakaoka** [comment]
Now the all three branches are destructively updated.
